### ISSUE TITLE
Adjusting the slime layer color to be distinguishable from all biome colors

### ISSUE THREAD

**Issue by BlueSteelAUS** [toolbox4minecraft/amidst#114]
slime chunk icon doesn't match what's displayed in the layers menu , suggestion change the menu to match what's actually used in the map for clarity,I'd also suggest making it fa different shade of purple to what colour used on mooshroom biome or something to make it stand out more on mooshroom biome because overlayed on mooshroom island edge its the same colour as the mooshroom island biome

**Comment by BigAlanM** [comment]
The slime chunk icon is a picture of a slime chunk.
The display is a violet square dot so that it contrasts with the biome colors of the map.
That makes perfect sense to me.
YMMV.

**Comment by BlueSteelAUS** [comment]
I think the icon ion the menu should be the pink/violet square so it matches just like everything else does.

you can't see the pink/violet square when its on a mooshroom island so something needs to change

**Comment by BigAlanM** [comment]
Will slimes spawn in a Mushroom Island biome?

**Comment by BlueSteelAUS** [comment]
don't know but they are showing in there i seen them with corners sticking out

**Comment by BigAlanM** [comment]
FYI - You CAN see that Amidst plots slime chunks in Mushroom Island biomes by hitting Ctrl_1, clicking on Highlight Biomes, and then clicking "Mushroom Island" on and off.

There is a definite problem with a conflict with the colors of slime chunks and Mushroom Islands.
They AREN'T exactly the same color but too close for casual differentiation.

**Comment by stefandollase** [comment]
I see both of you points. Yes, it seems kind of strange that the icon in the menu is different from what is used in the slime layer. However, the layer is supposed to not display icons like for villages or strongholds, but it should precisely highlight the blocks which belong to slime chunks. This makes it difficult to use the slime icon from the menu.

However, the current layer has indeed contrast problems with the Mushroom Island biome. I guess, that pink was chosen for the slime layer, because this biome is pretty rare: There might not be a color which can easily be distinguished from all biome colors. Thus, there are three solutions:

* Change the biome colors, so there is a color for the slime layer which can easily be distinguished from all the biome colors. I don't like this idea.
* Keep it as it is. I guess this will work, since it always was that way and the Mushroom Island biome is really rare. After all, you can use the Biome Highlighter to see the slime chunks in Mushroom Island biomes.
* Change the slime layer to draw a halve transparent, but structured icon. This should use at least two different colors. This will help to see the slime chunks regardless of the biome color. This will be the most complex change.

In my opinion, it is not too strange that the menu icon and the representation on the layer differ. Thus, I clearly prefer the second option: Just keep it as it is and use the Biome Highlighter to find slime chunks in Mushroom Island biomes.

If you find a better color for the slime chunk layer, don't hesitate to share it.

**Comment by BlueSteelAUS** [comment]
where is the slime chunk colour set so that i might experiment

**Comment by stefandollase** [comment]
It is set [here](https://github.com/toolbox4minecraft/amidst/blob/master/src/main/java/amidst/fragment/colorprovider/SlimeColorProvider.java#L10).

**Comment by BlueSteelAUS** [comment]
reinstalling github desktop (again) now. I hope i still remember how to use it

**Comment by BlueSteelAUS** [comment]
ok , installed maven , exlipse , created a fork of repo, and Got it to Compile and run :) 
i'm nowready to start fiddling :)

**Comment by BigAlanM** [comment]
I've found a color for slime chunks that contrasts adequately with ALL other colors used for biomes.
It's just a brighter pink than currently used.  
Here's an image that shows how this color contrasts with the default Amidst colors. It's the wide vertical lines.  
The RGB values are 254, 128, 250.
!http://i.imgur.com/vMbzMMQ.jpg

**Comment by BlueSteelAUS** [comment]
i just did a test with plain red , and worked well too. lol

**Comment by stefandollase** [comment]
Good work :-) I guess both of these would work. I added screenshots for each of the colors with the most critical biome near to it.

I will go with the pink color, since it is pretty similar to the current color.

![screenshot_default_6474846577619219886](https://cloud.githubusercontent.com/assets/981434/13569580/0f653ec2-e469-11e5-8652-0a4bd1636e73.png)
![screenshot_default_-2879903566397411747](https://cloud.githubusercontent.com/assets/981434/13569579/0f603440-e469-11e5-917f-343aea2e75d2.png)

**Comment by BlueSteelAUS** [comment]
ok I agree, though red is easier to see/distinguish when zoomed out , changed my fork to match

**Comment by BigAlanM** [comment]
So I can quite looking for a better color now?

**Comment by stefandollase** [comment]
@BigAlanM If you still don't like the new color, you can try to find a better one until the next release. However, I think the new color is good enough, because it is distinguishable from all the biome colors and quite similar to the old slime layer color at the same time. Thanks for finding it :+1:

**Comment by BigAlanM** [comment]
No problem, I enjoyed the challenge.
I now have the strangest Amidst Color spreadsheet you'll ever see.
I was actually calculating vector distances between 3D points to find an open spot in the RGB space to find an optimal color.
Then I realized that the transparency factor was complicating things.

**Comment by stefandollase** [comment]
@BigAlanM Sounds interesting :-D

I just created a new release Amidst v4.1 which contains changes which should have been in the v4.0 release. For more information please read the release notes. If there are no new bug-reports until the end of the week, I will announce it via the update functionality.

I adjusted the color with #127, which is included in v4.1. Thus, I close this issue.
