### ISSUE TITLE
Slime Chunks are incorrect in MC 1.9

### ISSUE THREAD

**Issue by Alex-R3CONN3R** [toolbox4minecraft/amidst#121]
Opened up Amidst v4.0 with MC Version 1.9 selected.
Seed Example: -3558144527798569323
At around 450 620 Amidst shows 5 nice adjacent slime chunks. No slimes spawn in the slime farm I built.
Made a superflat world with the same seed for testing.
Fenced off the chunks and no spawns again.
Using http://chunkbase.com/apps/slime-finder#-3558144527798569323 it shows that there are indeed no slime chunks.
At -2400 -816 Amidst shows some random slime chunks while Chunkbase shows 4 slime chunks in a square. Tested those in the same superflat world and slimes spawn plenty :(

Yeah something is off.

**Comment by stefandollase** [comment]
Thanks for the report. I must have changed some datatypes during the refactoring. The original Minecraft code uses an integer overflow and I accidentally replaced the datatype with long. It seems like we never checked that the slime chunks did not change.

Now, this code is tested and thus this should not happen again.

This will be fixed in the next release.

**Comment by Treer** [comment]
Heh! My slime farm wasn't working either, now I know how to fix it.

**Comment by stefandollase** [comment]
Yes, I'm sorry ...
