### ISSUE TITLE
New Developer Introduction

### ISSUE THREAD

**Issue by jmessenger235** [toolbox4minecraft/amidst#140]
Hello,

I'm Joshua Messenger. I'm a Software developer in the US. I have been doing some form of software development for the last 4 years and was taking courses for a number of months before that. My main work has been C# with some dabbling in Java, C/C++, and Javascript. I have done cross platform C# via Mono, but primarily have worked on windows applications and tools built on the .Net framework.

My main interest in amidst is in unit testing and in #120. Coming from a background in medical devices I have always enjoyed unit testing and improving quality. Additionally, as I enjoy Minecraft and finding good seeds, I am also very interested in that feature and am interested in potentially connecting it to Terrain control to add some dynamic capabilities. That would be a bit down the road though.

Thanks & Regards,
Joshua Messenger

**Comment by stefandollase** [comment]
Hey,

I am happy to see new developers coming to the project. Also, your experience sounds like it matches a Java project like this one :-) I think the only part that is very specific to Java is how we hook into the Minecraft jar file. If there is an issue with understanding some code, don't hesitate to ask.

Amidst uses Eclipse as an IDE. I am also going to push a concrete configuration for the Eclipse formatter, soon, so we all use the same code formatter. Since you are already familiar with Visual Studio, I guess you will quickly learn to use Eclipse.

Your main interest is unit testing ... wow! I am not sure if I ever heard this before :-P But don't get me wrong. Amidst can surely use more unit tests. I already covered the most important part of the code, which is the `World` object with all its pieces. However, there is still lots of untested code, so please go ahead :-)

#120 is indeed a very interesting upcoming feature. Sadly, I did not yet have the time to look at the implementation. I hope, I will get to this in the next few weeks. Nevertheless, the current implementation is supposed to be just a very basic prove of concept. I expect there to be quite a few decisions to be made as well as a discussion about these decisions. But first, I would like to review the current implementation.

I did not know Terrain Control. It sounds pretty useful for custom worlds. As always, before you start implementing a concrete feature, please open a new issue and describe your plans, so we can discuss it and agree on the changes.

Welcome to the team :-)

**Comment by jmessenger235** [comment]
Thank you for the welcome!

The main reason for a primary interest in unit testing is because I know from experience that is one of the best ways to get to know a project and a welcome starting point. There is nothing quite like it to force you to understand the code of a given application. I'll start looking into it in the upcoming week.

That feature definitely has some room to grow. I got some testing done and it does some very cool things.

Terrain Control is the bomb! And also a bit down the road, but I certainly will make sure to create an issue first.
