### ISSUE TITLE
Slime layer color and behavior

### ISSUE THREAD

**Issue by pokeball99** [toolbox4minecraft/amidst#141]
slime chunks in mushrooms islands are worthless anyways, due to nothing being able to spawn there besides passive mobs and( i think) mob spawners

**Comment by stefandollase** [comment]
Is there an issue with the new color? Even if it is not useful, I don't like to swap things back and forth that often.

Also, are you sure that slimes don't spawn in slime chunks in the Mushroom Island biome? I did not try this by myself.

see also #114

**Comment by BlueSteelAUS** [comment]
remember slimes will only spawn underground and below a certain level (other than in swamps). also not on a new moon i think from memory

**Comment by Pokechu22** [comment]
Slimes don't spawn in mushroom island chunks as far as the code is concerned.

BiomeGenBase.java (note that `Slime.class` is added to the `spawnableMonsterList` here; that's where they are registered).

```java
protected BiomeGenBase(BiomeGenBase.BiomeProperties properties)
{
    this.biomeName = properties.biomeName;
    this.baseHeight = properties.baseHeight;
    this.heightVariation = properties.heightVariation;
    this.temperature = properties.temperature;
    this.rainfall = properties.rainfall;
    this.waterColor = properties.waterColor;
    this.enableSnow = properties.enableSnow;
    this.enableRain = properties.enableRain;
    this.baseBiomeRegName = properties.baseBiomeRegName;
    this.theBiomeDecorator = this.createBiomeDecorator();
    this.spawnableCreatureList.add(new BiomeGenBase.SpawnListEntry(EntitySheep.class, 12, 4, 4));
    this.spawnableCreatureList.add(new BiomeGenBase.SpawnListEntry(EntityPig.class, 10, 4, 4));
    this.spawnableCreatureList.add(new BiomeGenBase.SpawnListEntry(EntityChicken.class, 10, 4, 4));
    this.spawnableCreatureList.add(new BiomeGenBase.SpawnListEntry(EntityCow.class, 8, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntitySpider.class, 100, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntityZombie.class, 100, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntitySkeleton.class, 100, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntityCreeper.class, 100, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntitySlime.class, 100, 4, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntityEnderman.class, 10, 1, 4));
    this.spawnableMonsterList.add(new BiomeGenBase.SpawnListEntry(EntityWitch.class, 5, 1, 1));
    this.spawnableWaterCreatureList.add(new BiomeGenBase.SpawnListEntry(EntitySquid.class, 10, 4, 4));
    this.spawnableCaveCreatureList.add(new BiomeGenBase.SpawnListEntry(EntityBat.class, 10, 8, 8));
}
```

BiomeGenMushroomIsland.java (note that `spawnableMonsterList` is cleared; also, this class is used for both the island and the shore; heights are changed between the two)

```java
public BiomeGenMushroomIsland(BiomeGenBase.BiomeProperties properties)
{
    super(properties);
    this.theBiomeDecorator.treesPerChunk = -100;
    this.theBiomeDecorator.flowersPerChunk = -100;
    this.theBiomeDecorator.grassPerChunk = -100;
    this.theBiomeDecorator.mushroomsPerChunk = 1;
    this.theBiomeDecorator.bigMushroomsPerChunk = 1;
    this.topBlock = Blocks.mycelium.getDefaultState();
    this.spawnableMonsterList.clear();
    this.spawnableCreatureList.clear();
    this.spawnableWaterCreatureList.clear();
    this.spawnableCreatureList.add(new BiomeGenBase.SpawnListEntry(EntityMooshroom.class, 8, 4, 8));
}
```

You can already see that slimes are excluded along with all other entities.  For completeness, here's EntitySlime.java:

```java
/**
 * Checks if the entity's current position is a valid location to spawn this entity.
 */
public boolean getCanSpawnHere()
{
    BlockPos blockpos = new BlockPos(MathHelper.floor_double(this.posX), 0, MathHelper.floor_double(this.posZ));
    Chunk chunk = this.worldObj.getChunkFromBlockCoords(blockpos);

    if (this.worldObj.getWorldInfo().getTerrainType() == WorldType.FLAT && this.rand.nextInt(4) != 1)
    {
        return false;
    }
    else
    {
        if (this.worldObj.getDifficulty() != EnumDifficulty.PEACEFUL)
        {
            BiomeGenBase biomegenbase = this.worldObj.getBiomeGenForCoords(blockpos);

            if (biomegenbase == Biomes.swampland && this.posY > 50.0D && this.posY < 70.0D && this.rand.nextFloat() < 0.5F && this.rand.nextFloat() < this.worldObj.getCurrentMoonPhaseFactor() && this.worldObj.getLightFromNeighbors(new BlockPos(this)) <= this.rand.nextInt(8))
            {
                return super.getCanSpawnHere();
            }

            if (this.rand.nextInt(10) == 0 && chunk.getRandomWithSeed(987234911L).nextInt(10) == 0 && this.posY < 40.0D)
            {
                return super.getCanSpawnHere();
            }
        }

        return false;
    }
}
```

The only conditions for slimes to spawn are below layer 40 in a slime chunk, or in a swamp between layers 50 and 70, dependent on how much moon light there is.  But, **that method is not called in mushroom island biomes** because slimes were already unregistered from the valid list for that biome.

**Comment by stefandollase** [comment]
@Pokechu22 Wow, I did not expect anybody to dig around in the code for this :-P Thanks. Nevertheless, I removed the actual code from your answer, since Mojang holds the copyright for the decompiled code.

However, until now, I only saw reasons why it did not make sense to change it in the first place. Is there a reason why it should be changed back? What is the issue with the new color?

**Comment by BlueSteelAUS** [comment]
so maybe the code for amidst needs to me changed so that it doesn't display those areas as slome chunks. to me its always a good idea to use the different (updated) colour as than you can see at the edges of the mooshroom biomes and a slime chunk sitting tight next to it. without having to toggle the slime blocks on'off i'd recommend leaving them the different colours

**Comment by Pokechu22** [comment]
@stefandollase I claim fair use :P  Generally, I think it's fine to post small snippets of the code (since it's not useful on its own) if it helps to explain ones point (I'm not sure how else I would have written it).

But overall, I think it might make sense to still display chunks there.  You just might want to have them displayed in a different way (possibly extra transparent?)

**Comment by stefandollase** [comment]
@BlueSteelAUS I don't like the idea to not display the slime chunks in the Mushroom Biome. People might want to use Amidst with a custom map, where biome information might be changed. Hiding slime chunks where Mushroom Islands are naturally generated might hide useful information for these people.

@Pokechu22 Yes, you might be right about the fair use. However, to my knowledge, fair use does not exist in all copyright jurisdictions. Thus, I generally prefer to be safe than sorry. Anyway, now we know that slimes don't spawn in Mushroom Island biomes :-)

As I already stated above, I agree with you that slime chunks should still be displayed in Mushroom Islands. Also, I think they should not have a different color. First, I think the meaning of the other color would be very unclear to most of the users. Second, the slime chunk layer is only supposed to display slime chunks. If it was supposed to display where slimes actually are able to spawn, it would need to color the swamp biome and it would also need to somehow add information about valid y-coordinates.

I think the current behavior is fine. Is there another argument to change something regarding the slime layer?

**Comment by BlueSteelAUS** [comment]
but amidst is for standard minecraft maps , no mods nothing special. so i can't see any reason to keep them being displayed on mooshroom biomes.  because they won't spawn there with out modification to the basic minecraft. as its not a valid slime chunk because of the code in original unmodified minecraft.(even stated on the wiki)  If we say because someone may tweak it so that they can , then its opening up the doors to display other tweaks / mods.. which its not supposed to do. where would you draw the line . ??  so i still reckon that amidst shouldn't show slime chunks on mooshroom biomes.

**Comment by Pokechu22** [comment]
There's a case where, in vanilla minecraft, biomes don't match.  For instance, an old world loaded on a newer version will have old biome IDs.  The slime chunks will still be the same, though.  And many _custom maps_ (which don't require mods to use or install) still change biomes, since biomes are stored in the world file.  Most importantly, _superflat_ still uses slime chunks.

There are cases where slime chunks are useful within what is normally generated as a mushroom island.

On the other hand, for the average user it's not too important.  So I think that they shouldn't be displayed too obviously (or else it should be clear that slimes don't spawn there).  But there isn't a very good way of indicating that, so to be honest, it's probably best to just let them render.

**Comment by BlueSteelAUS** [comment]
have them togglable in mooshroom biomes (defaulted to off) then. that way the average user won't see them in the mooshroom biomes. and for the rare special cases where they are needed to be seen you can turn them on, it shouldn't bee too hard to add in a toggle for those slime chunks on mooshroom biomes. theres still no need to change the color back. and this way when they do want to see those in mooshroom biomes that the match the other slime chunks :)

**Comment by pokeball99** [comment]
@BlueSteelAUS are you thinking of maybe some kinda debug keybind, or just throw it with the other debugish settings(max zoom and such)? if key bind, i'm thinking something like ctrl+s(or something else like that if thats already taken)

**Comment by BlueSteelAUS** [comment]
why not both have it hotkeyed and appearing on the menu. i'm always in favour of giving people options and configurability . rather then hard and fast thats it.

**Comment by stefandollase** [comment]
I like simple user interfaces. If we always add a setting when there is a discussion about whether or not to include or change a feature, then the settings menu would quickly grow in size and would be more confusing than it would be helpful. Also, if screenshots are posted it might be bad if it is unknown which settings are activate and which are not. So I think we should either display slime chunks in Mushroom Island biomes or we don't display them.

As stated above, I think we should just display them. One reason is because they might be needed in custom maps, where the biome information was changed. It is not only custom maps, but also maps which where generated by a very old biome generator.

The line between modded Minecraft and unmodded Minecraft is pretty clear for Amidst: The Minecraft profile that is selected cannot be a modded Minecraft profile. A save game must contain a valid `level.dat` as well as valid player information. That is all.

Regarding the color: I agree with @BlueSteelAUS that the color change was actually good, since it helps to see a difference between the Mushroom Island biome and the slime chunk which is directly next to the Mushroom Island biome.

Are there any more reasons for a change?

**Comment by BigAlanM** [comment]
This is a case where adding complexity to the program is not worth the effort and IMHO counter productive.  Just leave the current color as it is and just as is done for the fact that there are some false positives on surface structures note in the documentation that even though slime chunks are shown in Mushroom biomes slimes don't spawn there.
There may come a time when Mojang decides that slimes should spawn in the lower Y values of Mushroom biomes although I doubt it.

**Comment by BlueSteelAUS** [comment]
all it is is another option text would be like "SlimeChinks in mooshroom biomes"  it could be added into an advanced setting menu tab. if your going to support old beta stuff then i can't see your point about not making things too complex for the very few that'd use it. even the exporter function (which is actually supporting mods. lol custom maps is a mod especially if they are able to make it span slimes where mc doesn't. )   i don't really know of any mc version that ever allowed slimes to spawn in mooshroom biomes, if they are looking at a loaded map them the biomes would be relative to that version of mc. for uncovered chunks, and as for starting new maps in older version's same thing applies, i don't know of and mc version that did slimes in mooshroom biomes, yes you can use the mooshroom blocks in slime areas but that's still not a mooshroom biome, as soon as they change it to a mooshroom biome then slimes wont spawn there in vanilla mc, even in undiscovered chunks ,
even if you don't want it on a menu you can still have to settable in the text config file. I honestly can't see any harm in putting this in

**Comment by stefandollase** [comment]
@BlueSteelAUS
More options always means more complexity, because in theory you have to test your code with every possible combination of all options. So, if you add one boolean option, you double the number of test cases. Besides this, as I said, I like simple user interfaces, which means that there should not be an options for everything one can think of that would be "nice to have". Moving the option to a text file removed it from the user interface, but it really does not make it any better.

Next, custom maps are no mods. They might be created using a mod or an external tool, but they are used by a vanilla Minecraft installation. It is possible to change the biome information for already generated chunks.

I asked for reasons why this should be implemented. You answered with a description why it is not hard to implement it in your opinion. You also compared it with other features that are planned to be implemented. These other features are a better fit for the core functionality of Amidst and this is the reason why they get implemented.

Regarding the export functionality: This might not be part of the core functionality, however it helps the project to join forces if AmidstExporter is merged back into Amidst, so there is only one repository which has to be maintained.

Finally, I think there was enough discussion and possibility to convince me about the changes. As stated in the wiki:

> Describe the feature as good as you can. You can also create images to illustrate the description. We will then have a look at the request and decide whether the feature will be implemented. Please note that we decide if and when a feature is implemented.

The decision for this feature is that it will not be implemented. Thus I close this now.

@BigAlanM 
You are right, we should add documentation about this to the Wiki/FAQ. I added this to #66.
