### ISSUE TITLE
Slime chunks not the same in version 4.0 and 4.1

### ISSUE THREAD

**Issue by JelleBouwmans** [toolbox4minecraft/amidst#143]
Using this seed: -7445761358750870399

<b>V4.0:</b>
![image](https://cloud.githubusercontent.com/assets/17403041/14219380/32ef0ef4-f85a-11e5-80ca-8c4e510ac4fe.png)

<b>V4.1:</b>
![image](https://cloud.githubusercontent.com/assets/17403041/14219416/7aac4068-f85a-11e5-8302-f4eec42eed8a.png)

Which one is the right one? (I am halfway there digging a double slimechuck shown in the 4.0 version) The seed was generated in 1.9.0

**Comment by stefandollase** [comment]
There was a bug in Amidst v4.0 which displayed the incorrect slime chunks. However, this was quickly reported and fixed in Amidst v4.1. It now displays exactly the same slime chunks like Amidst v3.7.

See also the [release notes for v4.1](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.1) as well as #121.
