### ISSUE TITLE
Amidst crashes when opening a version of Minecraft

### ISSUE THREAD

**Issue by Enertoutpuissant** [toolbox4minecraft/amidst#163]
Here is a capture of the crash error:

http://www.noelshack.com/2016-17-1462103291-dcs.png

![dcs](https://cloud.githubusercontent.com/assets/18900098/14941627/300446fa-0fa2-11e6-8109-044ecab95d25.PNG)

Thank you in advance for your help,

Enertoutpuissant

**Comment by stefandollase** [comment]
I close this as invalid, because Amidst does not support modded Minecraft.

You can still use Amidst with an unmodded Minecraft profile. To do so, please create a new profile with the Minecraft launcher. Call it something like "Amidst" and use that when Amidst asks you for a profile. Make sure to select the correct Minecraft version when creating the new profile.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)

For more information, please read the FAQ: [Can I use Amidst with a modded Minecraft version?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#can-i-use-amidst-with-a-modded-minecraft-version)

Optifine might be supported in a future version, see #110
