### ISSUE TITLE
Amidst online

### ISSUE THREAD

**Issue by 2frei** [toolbox4minecraft/amidst#172]
Why don't you create a website with amidst ?
People enter MC version and seed number and the website display the map.

Because I imagine you have a real lot of bug tracking due to the numbers of different installs in many people PC, with different OS, different mods, etc.
I think it could be better and easier for you with this solution

**Comment by 2frei** [comment]
Ha and I just thought about one thing : money.
I DL amidst and so you're paid only one time : with the ad of the DL link.
But with the website, you can add some ads and you will be paid each time I need to use amidst.
And this tool is so useful, I think this money is not stolen ^^

**Comment by BigAlanM** [comment]
There are already sites that do that.
The problem with most of them is that you can't save the map except as a screen capture which limits the resolution of the resulting map.

**Comment by stefandollase** [comment]
For now, there are no plans to convert Amidst into a web application. There are already programs similar to Amidst that only provide a website, e.g. MineAtlas. I think, if anybody would like to convert Amidst to an online tool, they would have a lot of work to do. However, anyone can do it, since it is free and open source software. If you feel the need to do this, go ahead, but please let us know about your plans beforehand, so we can discuss whether it should be a part of this project or whether a fork should be created for it.

Nevertheless, I can see your point: Web applications have several advantages over locally installed applications. The biggest one is probably that they are always up-to-date and that we as the (only) operator can totally control the environment where the application is deployed to. Both of these are currently indeed the major cause for bug reports.

However, web applications have their own set of problems:

* You need to maintain a server, which costs money. For Amidst-type programs I think this is not as simple as it sounds: You have to generate the map on the server, because you cannot run the Minecraft map generator from the browser via Javascript. Thus, you cannot simply distribute static html/js/css via a content delivery network (like Github Pages), but your server has to execute some logic. As we can see with Amidst, this logic is quite CPU-intensive and because the server would be used by many people at the same time, it would have to be a big server or it would have to scale in size and now this gets complicated.
* A slightly less difficult issue is, that the server would have to have all available Minecraft versions installed.
* There is the additional risk of security issues, which is not that big of an issue with locally installed applications.
* As opposed to Java, I consider web development as a kind of unstable environment with many rapidly changing parts (different browser features and their standardization, security issues, many different libraries for the same thing and any of them might be outdated the next month, weak tool support). However, this might just be me being more used to the Java development.

After all, locally installed applications don't seem to be that bad. They can also be executed when you are offline, but you still can use the internet connection (if it is available) to retrieve current information. We already use this for the update mechanism and we plan to use this for more functionality in the future, see #146.

I don't think that old Amidst versions are that big of a deal, since Amidst has a pretty annoying update mechanism: If you use an outdated version, Amidst will tell it to you every time you start it.

We currently get the most bug reports for Amidst not being compatible with Optifine. However this might change in the future, see #110. Additionally, we plan to tell the user that modded Minecraft is not supported whenever an error occurs that is probably related to this. This will hopefully push down the number of bug reports that we receive due to modded Minecraft. Also, I don't see that big of an issue with these bug reports, because we have many information in the crash report which allows us to quickly identify and resolve these issues.

---

Where did you download Amidst? We don't provide a download link via adf.ly or similar services. The only place to download Amidst is currently [here](https://github.com/toolbox4minecraft/amidst/releases).

I also see your point with making money from Amidst via such a download link or ads on the website. Of course, it is always nice to get something back for the development and maintenance effort. However, I am not sure this is worth it. Here is why:

* Amidst has several developers, so the money would have to be shared. There are concepts like [BitHub](https://github.com/WhisperSystems/BitHub), but I am not sure whether this is appropriate for Amidst. In general I think the sharing would turn out to be difficult.
* Advertisements are the ulcer of the internet: Nobody likes them but everyone uses them to make money. They are simply annoying but not helpful at all. I am honestly not sure why it is possible to make any money with ads: I and pretty much nobody I know ever clicked on an advertisement.
* Nowadays adblockers greatly reduce the gain of ads.
* Ad networks create personal profiles for each user.
* Criminals more and more discover advertisement networks as a nice and simple way to deliver their malicious code to a great number of users, so the adblocker becomes the first line of defence.
* There might also be legal implications: I don't know where exactly is the line between commercial and non-commercial software. I have the suspicion that this line is not clearly defined. However, these two cases are often handled separately, e.g. if you use some libraries in commercial software, you need to pay for it, but it is free for non-commercial software. Mojang itself differentiates between commercial and non-commercial tools and they apply different restrictions for them. Thus, to prevent the additional organizational issues for commercial software, I am hesitant to even provide a donate button.

More information about ads:

* https://www.reddit.com/r/Minecraft/comments/4j4h9o/planetminecraft_asking_for_public_opinion_about/
* https://blog.stackoverflow.com/2016/02/why-stack-overflow-doesnt-care-about-ad-blockers/
* http://www.engadget.com/2016/01/08/you-say-advertising-i-say-block-that-malware/ 

I am not developing and maintaining Amidst because I want to make a living out of it. I came to the project, because I was interested in how it works. Then, I liked to practice my theoretical knowledge about software development and programming. Of course, this is not my first project, but I learned a lot of new stuff since I developed my last application. Now I get to know what it means to maintain a project with multiple developers, which is more difficult and time consuming than I thought, but which is nevertheless interesting to do.

So, after all I don't do it for the money, but because it is a lot of fun and I learn a lot. Also, I use Amidst by myself. If I want to make money, I should probably do something different and lets be honest: Sooner or later I will quit the project, because it is not interesting for me any more or I don't have enough time for it and someone else can make a better job at maintaining it. This is not planed yet, but this is how it will go. I think the project is setup in a way that it can easily be handed over to somebody else.

Not making money from Amidst of course also means that it is not that high of a priority for me, so if I have other things to do that are more important, interesting or fun to do, I won't have that much time for Amidst.

This reply became a lot longer than I intended it to be, so I will stop now. If you managed to not fall asleep while reading up to this point: Have a nice day :-)
