### ISSUE TITLE
Support for Minecraft 1.10 villages

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#177]
Minecraft 1.10 adds villages to more biomes. We should add this to Amidst.

**Comment by BigAlanM** [comment]
Actually, that should just be a toggle to turn off the part of the current Village mapping that filters out those that are too close to biome edges when using a post 1.9.4 profile and also adding the new permitted biomes.

**Comment by stefandollase** [comment]
@BigAlanM 
You might be right. I will look into this when I get the time for it, which is currently not the case.

**Comment by BigAlanM** [comment]
Is it possible to get a V4.2 Beta3 build out with this implemented?
There are a LOT of people on the forums that REALLY want closer to accurate PCMCv1.10 maps.

**Comment by stefandollase** [comment]
I guess they will have to wait. I am currently writing my semester exams, so I have to learn. Also, I am already putting time (which I don't really have) into the project with #120. I currently prefer #120, because there are more developers working on it, so I don't want to block them.

**Comment by BigAlanM** [comment]
It's been over two months since PCMCv1.10 came out (June 8, 2016).
Is there NO ONE with the knowledge and skill to tweak Amidst to accurately (or at least close) map villages in 1.10?
When this repository was started I was overjoyed that someone was going to take over for the beleaguered original programmer.
All I've seen is people hung up on expanding the functions of the program and absolutely NO support for the thousands upon thousands of loyal users that expected more timely updates.
I'm truly disappointed with you all.

**Comment by ForestFeather** [comment]
This project is free, done by volunteers.  There is no real way to 'easily' determine this information, as the code that there is access to is in fact obfuscated to make understanding it harder.  Insulting the developers who do take the time to try and figure it out makes them less likely to do so.  So please don't try to act like a disappointed manager or worse, disappointed parent, and don't make claims that you speak for others.

If the issue is that important to you, you can research the algorithms that are used yourself to help provide the information to those whom may not have the skill/time but still have the programming experience, or even implement it yourself if you can code.  This is the joy of open source programs!

**Comment by BigAlanM** [comment]
There were over a half a MILLION downloads of the last version of Amidst that was on Bitbucket.
Unfortunately Github doesn't record the number of downloads.
So I'm pretty sure that I do speak for, at least, thousands of Amidst users.
Believe me, if I were still into programming (I last drew a paycheck as a programmer nearly 20 years ago) and if I could wrap my head around Java code, I would.  However, I became a systems analyst, and have relegated actual programming to younger and more agile minds.

**Comment by ekevoo** [comment]
No one is drawing a paycheck working on Amidst, and legal complications make this unlikely to happen.

Number of users is completely irrelevant to a free project, too. Whoever is available to help coding helps, whoever isn't should help by not being a problem.

**Comment by BigAlanM** [comment]
I asked someone who I know has a good grasp of the Minecraft world generator code for his input.
Here is his reply:
I don't have MCP for 1.10 but it looks like they removed code that checked for a valid biome within the bounding box of each individual village component. Notably, the area checked was a square radius based on the longest dimension / 2 plus 4 blocks in each direction, so a 35 block long path (the longest single section) would have a 42x42 block square around it checked, and not be generated if any block within that area was in an invalid biome, so in the worst case a village would need an area as large as 90x90 blocks (the well is 6x6 blocks) in order to generate. The relevant code is in StructureVillagePieces, getNextVillageStructureComponent and getNextComponentVillagePath (these are nearly identical, I only show the first one):

private static StructureComponent getNextVillageStructureComponent(ComponentVillageStartPiece par0ComponentVillageStartPiece, List par1List, Random par2Random, int par3, int par4, int par5, int par6, int par7)
{
    if (par7 > 50)
    {
        return null;
    }
    else if (Math.abs(par3 - par0ComponentVillageStartPiece.getBoundingBox().minX) <= 112 && Math.abs(par5 - par0ComponentVillageStartPiece.getBoundingBox().minZ) <= 112)
    {
        ComponentVillage var8 = getNextVillageComponent(par0ComponentVillageStartPiece, par1List, par2Random, par3, par4, par5, par6, par7 + 1);

        if (var8 != null)
        {
            int var9 = (var8.boundingBox.minX + var8.boundingBox.maxX) / 2;
            int var10 = (var8.boundingBox.minZ + var8.boundingBox.maxZ) / 2;
            int var11 = var8.boundingBox.maxX - var8.boundingBox.minX;
            int var12 = var8.boundingBox.maxZ - var8.boundingBox.minZ;
            int var13 = var11 > var12 ? var11 : var12;

            if (par0ComponentVillageStartPiece.getWorldChunkManager().areBiomesViable(var9, var10, var13 / 2 + 4, MapGenVillage.villageSpawnBiomes))
            {
                par1List.add(var8);
                par0ComponentVillageStartPiece.field_74932_i.add(var8);
                return var8;
            }
        }

        return null;
    }
    else
    {
        return null;
    }
}

Also, in my 1.6.4 Survival world 5 out of 16 villages listed in Village.dat do not exist so it appears that about 1/3 of villages do not generate due to the biome restrictions (this proportion is probably lower in 1.7-1.9 due to the clustering of hot biomes effectively making them larger); with the aforementioned change in 1.10 virtually all villages should exist unless they changed something else (there is still a slight chance that one may not, based on the fact that you can rarely find mineshafts that do not have any corridors, only a central room, because the game tries to add corridors with random orientations and they do not generate if they intersect the central room. The only randomly generated structure that I know of that is guaranteed to fully generate is strongholds, which will recreated until an End Portal room has been added).

Does this help???

**Comment by stefandollase** [comment]
@BigAlanM
First of all, if you want to criticize the community of this project, please do so in a new issue! Don't spam existing issues with it. You already expressed your frustration in #219 and #220. This is the third issue that has to suffer from an off-topic discussion.

---

This is a free and open source software project. Nobody here receives any money for what they are doing. The project does not make money from advertisements and it does not accept donations. The only donations that are accepted is the time and effort that people put into the project. Everyone has their own reason to do so, for example some community members are only interested in specific features and others just want to practice their skills or even expand them.

Thus, you cannot force community members to do what you want. You cannot force them to work on specific features and you cannot force them to put more time into the project. The only thing you can do to push a specific feature forward is to put time and effort into it by yourself. If you are not willing or able to do so, please don't expect it from other community members. Not having the required skill-set for the feature does not change this.

Of course, everyone is welcome to express their opinion about what they think is more important to do and indeed, you did it for this issue, which is good. I also agree with you that many users would like this issue to be resolved, however this does not change anything of what I said above: You cannot force anyone to do what you would like them to do.

The only thing that you reach with this discussion is to spread a bad mood in the community. This does not help anyone, but it makes it more likely that people lose interest in the project, because it is not fun anymore.

---

That being said, I can also say about myself that I thought I would have more time for the project. I think leading this project requires more time than I am able to put into it. Thus, it would probably be the best to pass the project leadership over to another member of the community, which is able to spent the required time. However, I don't think this is gonna happen soon, because first I still find it interesting to do what I do, second I don't see a community member that is an obvious choice for the leadership and third I don't think the project is currently in a good state to hand it over. So, for now we all have to accept that this project is going at a slow pace.

**Comment by stefandollase** [comment]
@BigAlanM
Thanks for the information! It is great to see you help to resolve this issue. However, there still needs to be someone that spends the time and effort to actually figure it out for Amidst, so again: Please don't expect it to be done tomorrow.
