### ISSUE TITLE
How do you zoom again?

### ISSUE THREAD

**Issue by hgreatrex** [toolbox4minecraft/amidst#187]
Hi - I'm going crazy and I seem to have forgotten the keyboard command to zoom in and out of the AMIDST map (on a mac - AMIDST 4.1).  Could someone remind me?

I know it's intuitive, but would it also be possible to put it in the wiki for the next time someone forgets?
Thanks!

**Comment by stefandollase** [comment]
In v4.1, the keyboard zoom is broken. It was fixed in v4.2-beta1. The keys are `+` and `-`. Alternatively, you can simply use the scroll wheel.

Adding the shortcuts to the wiki is already on the todo list, see #66.

**Comment by sab39** [comment]
Some laptops with touchpads don't have a scroll wheel equivalent so the workaround of using the scroll wheel isn't available to everyone. As far as I can tell I have no way of zooming in at all on the current release version.

(As a programmer myself, I know that it's annoying and rude when users comment on bugs that are already fixed complaining that they aren't in a released version yet, and I'm not trying to be _that user_, but I thought you might not be aware that some people can't use the workaround, in which case hopefully that'd be useful information to you rather than just a complaint, and might make a difference to how much priority you place on releasing a final version of 4.2 with the fix)

**Comment by stefandollase** [comment]
@sab39 
I don't mind comments on closed issues as long as they are on-topic, which is the case for your comment :-)

I am aware that 4.1 has this issue. However, the policy is, that each new stable minor version is announced via the update mechanism. Since no new features and no important bug fixes are implemented for 4.2, I decided to not release it yet. It would probably just annoy the majority of the users, because the update mechanism is manual and the update announcement can be quite annoying. It is especially annoying if it keeps popping up whenever the user opens Amidst (They released a new version again ... really?). If we do this too often, many users will just ignore the update announcement, which is not desirable. Thus, we should try to keep the *update spam* to a minimum. Nevertheless, I released beta versions, which contain the bug fixes, but which are not announced as an update. This has the advantage that everyone how is experiencing the issue can already update to the new version, while the majority of the users is left alone.

**Comment by sab39** [comment]
I understand the reasoning for not making a new release. The reason I suggested it was that my first reaction when I discovered that zooming wasn't working was to use the "check for updates" option to look for a new release that fixed the bug. After that I looked on the website and the wiki and couldn't find anything about how zooming is supposed to work. It took me a lot of searching to find the issue in the bug tracker and the beta releases with the fix. I also was nervous about downloading a beta release because I thought the reason it wasn't a final release yet was because it was still unstable or buggy.

Maybe putting something more prominent on the website to say "If you're having problems with zooming, use the Beta version" would be a good way to make sure people don't get stuck?

**Comment by stefandollase** [comment]
Thanks for point out your view. As a developer, I am fairly used to use Github and search for existing issues, thus I tend to forget that not everybody is familiar with this kind of stuff. Until we release Amidst v4.2, this issue as well as #194 should help other users to find the beta release.
