### ISSUE TITLE
Provide buttons in the UI for zooming as well as the keyboard and mouse shortcuts

### ISSUE THREAD

**Issue by sab39** [toolbox4minecraft/amidst#194]
Having `+` and `-` buttons like Google Maps does would make the zoom functionality more discoverable. (Not to mention making it usable even when the keyboard shortcuts are broken and you don't have a mouse with a scroll wheel!)

**Comment by stefandollase** [comment]
Without looking into the code, I think this should be doable with reasonable effort. However, I think I prefer to have as little widgets covering the map as possible. Thus, I would like to know your opinion about my alternative solution: We can convert the `+` and `-` keys to menu entries with keyboard shortcuts like `Ctrl++` and `Ctrl+-`. This makes them easily discoverable and less probable to break, since we use keyboard shortcuts for menu entries for many more things.

**Comment by sab39** [comment]
Menu items would be a decent compromise solution. Personally I think buttons would be better, but that's just my preference; having menu items would solve the problem of "I can't zoom AT ALL!" which is the important part!

**Comment by stefandollase** [comment]
This is implemented by #283.
