### ISSUE TITLE
Amidst Crashing On Profile Select

### ISSUE THREAD

**Issue by WolfyFriend** [toolbox4minecraft/amidst#211]
All it says is "Unable to create local Minecraft interface."

**Comment by stefandollase** [comment]
Hmm, I guess that is not good. The error is thrown [here](https://github.com/toolbox4minecraft/amidst/blob/96766fac398c3a3b44bbfee831a40fc4ee4a59f8/src/main/java/amidst/mojangapi/minecraftinterface/local/LocalMinecraftInterfaceBuilder.java#L46) and displayed [here](https://github.com/toolbox4minecraft/amidst/blob/96766fac398c3a3b44bbfee831a40fc4ee4a59f8/src/main/java/amidst/gui/profileselect/LocalProfileComponent.java#L87). Sadly, we only display the error message in the GUI, but not the stacktrace. However, we need to see the stacktrace to be able to locate the actual error. The stacktrace is written to stderr. To see it, you should run Amidst from the command line. The error will then also be displayed on the command line.

Thus, I ask you to run Amidst from the command line and to post the error message into this issue. Do you know how to do this?

Also, which Minecraft version do you want to use? Is it a modded profile?

**Comment by stefandollase** [comment]
I just released [Amidst v4.2-beta3](https://github.com/toolbox4minecraft/amidst/releases/tag/v4.2-beta3). Please let me know whether the issue still exists.

**Comment by stefandollase** [comment]
In the new release, I added a menu entry to display all log messages. If the issue still exists, please copy the complete text into this issue.

```
Help > Display Log Messages
```

**Comment by Quenntinne** [comment]
![screenshot_39](https://cloud.githubusercontent.com/assets/23644098/20502922/94cfb5f8-b040-11e6-8c76-61eaa2434f55.png)
I have a problem in the "Select a minecraft profil" to

**Comment by MattSturgeon** [comment]
@Quenntinne it looks like you might not have a vanilla profile? I am not sure what `Quenntinne` means, but AMIDST needs a normal unmodified minecraft version to work.

You should use the minecraft launcher to make a profile that uses version 1.10 (or some other unmodded version directly from Mojang). _Note that if you want to use 1.11 you will need to use AMIDST [4.2-beta3](https://github.com/toolbox4minecraft/amidst/releases)._

Finally, next time you have an issue that isn't already reported, please use the "New issue" button, instead of commenting on on a related (though not the same) issue.

**Comment by stefandollase** [comment]
@Quenntinne
I just reworked the [Using Amidst](https://github.com/toolbox4minecraft/amidst/wiki/Using-Amidst) wiki page. Maybe, it helps you to resolve the problem. If not, please create a new issue and if possible provide more details.

**Comment by Quenntinne** [comment]
@stefandollase  thanks i just created a new profil and it's working now :)

**Comment by stefandollase** [comment]
The OP seems to have lost interest in this issue. Thus I close it.

**Comment by StanlyLife** [comment]
issue still persists
