### ISSUE TITLE
Warning needed for moving player

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#239]
I just tried moving a player in a displayed world.
The program doesn't tell the user that the world file can not be in play (open) in Minecraft.
To work the user needs to save and close the world,
load the world information into Amidst with Ctrl-o or the menu,
Make the player move as instructed,
save the moved player world,
then reopen the world in Minecraft.

**Comment by stefandollase** [comment]
The warning that is displayed can be found [in the FAQ](https://github.com/toolbox4minecraft/amidst/wiki/Using-a-Save-Game#what-information-is-written-to-the-save-game). The last sentence of this warning tells the player to not have the save game opened in Minecraft at the same time:

> Especially, make sure to not have the save game loaded in Minecraft during this process.

Can you clarify what is the missing information?

**Comment by MattSturgeon** [comment]
I suspect this issue is really about warning users using a dialogue.

Personally I would consider the dialog box warning uneccessary, and would like a (ticked by default) "never show this warning again" checkbox if implemented.

**Comment by stefandollase** [comment]
@MattSturgeon
I guess the checkbox would be a separate feature request?

**Comment by BigAlanM** [comment]
There is a warning (easily overlooked) in the dialog that pops up if you click World>Save Player Locations or hit Ctrl-S  but there is no indication of this warning in the instructions that pop up when you click World>How can I move a player?

**Comment by stefandollase** [comment]
@BigAlanM
So this is a feature request to adjust the [How can I move a player?](https://github.com/toolbox4minecraft/amidst/wiki/Using-a-Save-Game#how-can-i-move-a-player) text, to include a hint that the world cannot be used by Minecraft at the same time? What is the advantage of duplicating that information from the warning message?

**Comment by BigAlanM** [comment]
Quite frankly I expect detailed instructions to have ALL the proper steps to take to accomplish the task.
The fact that the step of closing the Minecraft world isn't listed caused me to be quite confused when my location didn't change.

**Comment by stefandollase** [comment]
There is no missing information. [How can I move a player?](https://github.com/toolbox4minecraft/amidst/wiki/Using-a-Save-Game#how-can-i-move-a-player) is supposed to describe how to tell Amidst that a player should be moved. The warning from [What information is written to the save game?](https://github.com/toolbox4minecraft/amidst/wiki/Using-a-Save-Game#what-information-is-written-to-the-save-game) gives additional information about what the user needs to check to ensure that the save operation works flawlessly. It also contains information about what happens in the error case. I think this structure is fine. Especially, because there is nothing special for Amidst: People that frequently work with map editing tools know that they have to unload the save game in all other programs to ensure that the save operation works successfully.

I do not want to duplicate information, since duplicate information means that there is more text in general, which means less users will read the text. There will always be users who fail to read the given information. Increasing the overall amount of text will only increase the number of these users.
