### ISSUE TITLE
Tie "Open World File" to save path in Profile information

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#26]
Title says it all.
I don't know if others do it.  But pretty much ever since the launcher with profile system came out I've been making separate save folders each time the MC world generator changes or there is a meaningful change in a MC version.
ie. I started a new folder for MCv1.8.x worlds because of the introduction of Ocean Monuments.
By doing this I prevent shooting myself in the foot by accidentally creating new chunks in a world that aren't compatible with the original world as created.
Since Amidst reads the Profile information is should be REASONABLY easy to change the save folder from the default to the one used dictated by the profile if, in fact, the user has checked the "Game Directory:" option.

**Comment by stefandollase** [comment]
I have to say, I am a bit surprised about this bug report, because this should already be implemented. I use different profile directories for all of my profiles. Even the old Amidst 3.7 opens the saves folder that belongs to the selected profile.

I guess this is also related to the windows "feature", already mentioned in #12 ;-) It always opens the directory that is was last set on. Anyways, I will look into this issue and I will try find a fix for this.

**Comment by stefandollase** [comment]
I was not able to find anything about this being a known issue with the `JFileChooser` on windows. I implemented a possible fix for this in #29, which is included in the new v4.0-beta5 release. Can you try whether this is still an issue there? Also, please make sure the saves directory exists in the profile directory. If it does not exist, it is platform dependent which location is opened.

**Comment by BigAlanM** [comment]
stefandollase you may be correct. I most likely assumed something that I wasn't even seeing.
I have since checked and it's because the Open file dialog doesn't show the folder path I mistakenly thought it was going to the main saves folder under .minecraft, it isn't it IS, in fact, going to the proper saves folder for that profile.
This is a non-issue. Please close this.
