### ISSUE TITLE
Possible unintended code changes

### ISSUE THREAD

**Issue by ArgTang** [toolbox4minecraft/amidst#289]
in #269 @moulins did some refactoring, amongst them  changed  RealClassDetector.java to a functional interface. 

In the codeformating pull request #286 changed this it back again to a class. 
This Issue is to confirm that the changes in #286 is intentional, and not a unintended sideeffect

**Comment by stefandollase** [comment]
I did not expect anyone to review the changes. I appreciate it :-)

Indeed, this was an intended change. I created commit f34fb54 only to remove the usage of default methods. Because this is a coding style thingy, it somehow fits into the reformatting branch. I removed the usage of default methods, because that is not how they were intended to be used. They were only introduced into Java to allow interface evolution, so you can still add methods to an interface that is published and implemented by a third party. Instead, the  `RealClassDetector` [now takes](https://github.com/toolbox4minecraft/amidst/pull/286/commits/f34fb54fbbb4bb9521d1fd8ffdfde6c5adbdf1d8?diff=split#diff-adef058a7fdcd0bc99c6daf719d492c2R12) a `Predicate<RealClass>`, because that is really what is passed into the `ifDetect` method. This also fits the principle of preferring a use relationship over inheritance.

In [his SO-answer](http://stackoverflow.com/questions/28681737/java-8-default-methods-as-traits-safe/28684917#28684917), Brian Goetz (a Java Language Architect) explains the rational behind introducing default methods.
