### ISSUE TITLE
I cant open 1.8.8 game

### ISSUE THREAD

**Issue by dotEagle** [toolbox4minecraft/amidst#297]
the used operating system and version: Windows 7 64bit
the used Java version: 64bit
the used Minecraft version: 1.8.8
the used Amidst version: v4-2
the error message, if any: https://gyazo.com/22c126fb680d81af901bc8b7adf1e8ec
What did you do to produce the error? clicked on the place where it said '' eaglesausage ''
(How) can the error be reproduced? by clicking on it again
What did you expect to happen? To start the map
What did actually happen? the error

**Comment by stefandollase** [comment]
I close this as invalid, because Amidst does not support modded Minecraft.

You can still use Amidst with an unmodded Minecraft profile. To do so, please create a new profile with the Minecraft launcher. Call it something like "Amidst" and use that when Amidst asks you for a profile. Make sure to select the correct Minecraft version when creating the new profile.

![minecraft launcher](https://cloud.githubusercontent.com/assets/6390507/14304860/0cd746e8-fbfa-11e5-8451-e5f97cdeeb03.png)
