### ISSUE TITLE
ps4 support?

### ISSUE THREAD

**Issue by Netherstarfall** [toolbox4minecraft/amidst#298]
is there ever going to be ps4 support? not really a issue just a suggestion ps4 support for this would be really cool!

**Comment by stefandollase** [comment]
Nope.

https://github.com/toolbox4minecraft/amidst/wiki/Using-Amidst#what-minecraft-versions-are-supported

**Comment by Netherstarfall** [comment]
why though? it doesn't really explain why on there all it says is because of minecraft biome generation if you wanted to you could figure out a way are you just being lazy then? like just a nope? really?

**Comment by stefandollase** [comment]
No, I am not being lazy. I put much of my rare time into this project. However, this time is still limited. Supporting another version than the Java version of Minecraft requires a lot of work, since (to my knowledge) all other versions are not written in Java, but C or C++ which makes it much more difficult to hook into. So I guess if you want to have PS4 support, you will have to implement it by yourself ... or are you being lazy? ;-)

**Comment by CubeTheThird** [comment]
The reason why there can even exist a mapper for the PC edition is because the existing code and software can be used to render what the terrain will resemble. Last I checked, the console edition doesn't have such available software or tools.
