### ISSUE TITLE
Change zoom controls to CTRL + and CTRL -

### ISSUE THREAD

**Issue by Creeperman8362** [toolbox4minecraft/amidst#300]
Those zoom controls are the same for nearly all software, and yet Amidst uses CTRL G and CTRL H. It only makes sense to add CTRL + for zoom in and CTRL - for zoom out. Most people are used to those keys for zooming, and it's frustrating and annoying when they don't work in Amidst.

**Comment by stefandollase** [comment]
I agree that this is unusual and annoying. I also wanted to use CTRL + and CTRL -, however there does not seem to be an easy solution for this with our current GUI framework (Swing) so I chose to use CTRL+G and CTRL+H. We already had issues with + and - as shortcuts (#134), however we were able to fix these. Now, I switched the shortcuts again, because of #194. I did not find an obvious way to create the CTRL + or CTRL - keyboard shortcut for a menu entry that works for all keyboard layouts and all operating systems. Searching for this I did indeed find other people having the same issue and nobody seemed to have solved it properly. Thus, I decided to go with CTRL+G and CTRL+H, because these work just fine.
