### ISSUE TITLE
Suggestion: Starting a new thread on www.minecraftforum.net

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#33]
The current thread, http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder,
is currently at 5095 posts in 253 pages and was started on #1  Sep 14, 2011 when PCMC Beta version 1.8 was about to come out.

I think it's about time to start a new thread with the release of Amidst v4.1.

The question is where to put the thread.
I guess it should be in that forum but I'm thinking of also starting a thread in the PC Seeds forum
http://www.minecraftforum.net/forums/minecraft-discussion/seeds since AFAIK Amidst only runs on PCs and Macs.

**Comment by stefandollase** [comment]
Since I am completely inactive in the minecraftforum, I do not really have an opinion about that. I do not even have an account for it. Maybe @skiphs or @Treer have an opinion?

**Comment by Treer** [comment]
We definitely need to start a new thread when it's released, because we don't have the ability to keep the details updated in the first post of the Amidst thread.

My instinct is to put it in mapping and modding - the same place as Amidst, and create a post linking to it in PC Seeds forum. Because Amidst has general usefulness and appeal, rather than just to seed hunters/collectors.

**Comment by stefandollase** [comment]
Good, since you both share the same opinion, it seems to be clear that we need a new thread.

Another thing we should talk about is where to collect information. While the forum is fine to talk directly to the users, I do not think it is a good platform to build up good documentation. This is because everything just vanishes in all the other posts, independent from how useful the information was. I guess, even the first post of the thread can only be updated by the original author (is this true?).

My suggestion is to use [the Github wiki](https://github.com/toolbox4minecraft/amidst/wiki) to build up documentation about Amidst. I already created a few pages in it. The good thing about it is, that everything we put it there is easy to find later. Probably the best thing is, that you can write good answers to common questions in the wiki. When somebody asks such a the question, you can just refer to the wiki, so you do not need to repeat yourself over and over. Maybe, some users are able to use a search engine, so they will find the wiki entries by their selves. Also, the wiki can be edited by everyone (I think), which also enables non-collaborators to create documentation.

Thus, my suggestion is to post a forum entry that is similar to the readme in this repository. What I mean by that is, that it should be designed to not change frequently. We should just put some links in it and a short description that is still valid in the future. However, maybe I am completely wrong about this? After all, you collected more experience with the forum. What do you think?

Also, we should make a decision who creates the post, to prevent multiple posts. I can create a forum account and the post (if you send me the link to the correct sub-forums). However, I will probably write the post in this Github issue first, to get your feedback about it.

**Comment by Treer** [comment]
I'm a big fan of wiki's, and the lack of good Amidst documentation has been bothering me for a while - at one point I even had [a feature request for a feature that already existed but which you had to read the source code to know about!](https://github.com/Treer/AmidstExporter/issues/1). So yeah, consolidating documentation in the wiki is something I've been meaning to do for a while.

I can't tell if the Amidst4 wiki is editable by everyone, I think that's off by default - you'll have to check the project's settings. Editable by everyone is preferable - we can always re-evaluate if that starts causing problems, but I doubt it will.

Since you don't have a MinecraftForum account, may I suggest creating a toolbox4minecraft account instead of a stefan account, or both. That way its credentials could be made available to someone else if you ever wanted to move on from the project, and in the meantime you could still post in the forums as yourself. Perhaps tie them together using the same icon for both accounts so the toolbox4minecraft account posts the minimal first post with links, but if you wanted to join in as yourself, you could.

**Comment by stefandollase** [comment]
@Treer The feature request is indeed kind of funny :D

Good to know that we share the same opinion about the wiki. I just enabled it to be publicly editable.

I like your suggestion to create a toolbox4minecraft account. Indeed, I like it so much that I also created a toolbox4minecraft mail address. It is toolbox4minecraft@gmail.com. However, I would like to publish it as toolbox4minecraft+amidst@gmail.com. Mails to this address will be delivered to the toolbox4minecraft@gmail.com address. This is a [feature of gmail](https://support.google.com/mail/answer/12096?hl=en). It enables us to get an idea of where mails come from. So, If you are asked for the mail address, please just talk about the address **toolbox4minecraft+amidst@gmail.com**.

I also created the toolbox4minecraft account in the minecraftforum, but not yet the new thread.

**Comment by stefandollase** [comment]
# Amidst has found a new home.

Since Skidoodle (aka @skiphs on Github) is to busy to maintain Amidst, it was moved to a new location. It has also found some new developers. One of them is DrFrankenstone (aka @Treer on Github) who is the developer of AmidstExporter. We aim to completely merge AmidstExporter back into Amidst. We are currently about half way done with this.

### Important Links

* [Project Page](https://github.com/toolbox4minecraft/amidst)
* [What is Amidst?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#what-is-amidst)
* [FAQ](https://github.com/toolbox4minecraft/amidst/wiki/FAQ)
* [Wiki](https://github.com/toolbox4minecraft/amidst/wiki)
* [Download](https://github.com/toolbox4minecraft/amidst/releases)
* [Report a Bug](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#how-can-i-report-a-bug) - please report bugs, so we can fix them
* [Request a New Feature](https://github.com/toolbox4minecraft/amidst/issues/new)
* minecraftforum thread
* [Getting Involved](https://github.com/toolbox4minecraft/amidst/wiki/Getting-Involved)
* [Directly Contact the Developers](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#how-can-i-get-in-contact)

### Link Archive

* [Old Project Page](https://github.com/skiphs/AMIDST)
* [Old minecraftforum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262200-v3-7-amidst-strongholds-village-biome-etc-finder)
* [Project Page of AmidstExporter](https://github.com/Treer/AmidstExporter)

### Legal Information

Amidst is not owned by or related to Mojang in any way.

Amidst comes with ABSOLUTELY NO WARRANTY. It is free and open source software, licensed under the GPLv3, [see the license text](https://github.com/toolbox4minecraft/amidst/blob/master/LICENSE.txt).

---

This is the message I plan to post to the minecraftforum. Please have a look at it and tell me what you think. Especially give feedback about missing information as well as typos and incorrect grammar. Also, what do you think about the title? It is fitting for the moment, but not in the long run. Can the title be changed later on?

I will add the link to the new minecraftforum thread to this list and to the [How can I get in contact?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#how-can-i-get-in-contact) section of the FAQ, when it is created. I will also update the links in the README.

**Comment by stefandollase** [comment]
@BigAlanM I had a look at the forum structure and I also think we should create the new thread in the same sub forum as the old thread. You suggested to create another thread in the pc-seeds forum. Currently, I think we should not do this, simply to have a single place for the conversation about Amidst. Do you think there is an advantage in creating another post in the pc-seeds forum?

**Comment by stefandollase** [comment]
After looking at [the Rules](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2601515-mapping-and-modding-rules) I need to also include a link to the [What is my internet connection used for?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#what-is-my-internet-connection-used-for) section of the FAQ, as well as a screenshot of Amidst.

**Comment by Treer** [comment]
Is the purpose of this post to get people to help out with the project, or the make them aware of the "product"? 

if the later, then don't post until there's a full release people can download, don't make the release sound half finished (don't let the AE export menu hold up the full release). Prioritise the description and binaries, perhaps a screenshot, and list the project information and links further down.

The title is editable, so your current title is good.

I'm not a denizen of pc-seeds subforum, but I suspect there is advantage in creating another post in there - it could announce the news and link back to the main post.

**Comment by stefandollase** [comment]
The post should only make them aware of the new project. The description about how they can contribute is just a secondary goal.

I also think, we should wait for the stable release and then post to the forum. I will try to change the post so it does not sound half finished (that is indeed a good hint!). In my opinion, we can go for the stable release this week. Maybe we wait for the next Minecraft snapshot. Do you think we should do anything before we release the stable version? Most of the open issues are feature requests. The others are currently not easily resolvable and would thus move the stable release further in the future.

Do I understand you correct, that you think I should include the description from [What is Amidst?](https://github.com/toolbox4minecraft/amidst/wiki/FAQ#what-is-amidst) directly into the post? Should I include direct download links or is it enough to link to the releases page?

Okay, I will think about a good second post for the pc seeds forum, that has a clear focus on the seed finding functionality.

**Comment by Treer** [comment]
A link to the releases page is best because it's always pointing the lastest binaries.

Not all Minecraft players have heard about Amidst or what it is, so there should be a description near the top, but brief, perhaps just the "What Amidst can do for you" section with a "detailed description" link that goes to the full "What is Amidst" page.

After intial interest from the forum post has died down, we should also ass it to the Minecraft wiki: http://minecraft.gamepedia.com/Programs_and_editors/Mapping
(May as well stagger the annoucements incase some issue is uncovered when people start using it)

**Comment by Treer** [comment]
> Do you think we should do anything before we release the stable version?

I think wait until we know what's happening with [the stronghold locations bug in the 1.9 snapshots](https://bugs.mojang.com/browse/MC-92289). If it looks like 1.9 is going to contain this bug then release Amidst as it is, if it looks like they will fix it before 1.9 then hold off the release until we find out what they're changing it to. Either way we should be able to release a stable version before 1.9 comes out.

**Comment by stefandollase** [comment]
Okay, I created a wiki page for the new draft of the minecraftforum thread [here](https://github.com/toolbox4minecraft/amidst/wiki/Forum-Entry-%28will-be-deleted-from-the-wiki%29). It contains detailed information about Amidst. As well as everything that is required by the rules. Feel free to suggest further changes. You can also go ahead and edit it directly, since the wiki has a commit history. I also plan to update the README to contain the exact same content.

Good idea to include the new links to Amidst into the minecraft wiki. Should we update the existing entry or create a new one? I think we should update the existing one, since we decided to keep the name and @skiphs agreed to the moving and is still an owner.

Good point to wait for how they handle the bug. I will go ahead and create an issue in this project, so we don't forget about it, which already happened to me :-P

I also agree with you that we should be ready to release the stable version as soon as Minecraft 1.9 is out.

**Comment by BigAlanM** [comment]
@stefandollase As to your question about who can edit posts in a thread.  
1. Obviously the person that makes the post can edit it any time they wish unless a higher power locks the thread.
2. The "higher powers" are any of the forum administrators and any moderator for the forum section that the thread resides in.
In the case of the original Amidst thread that means Skidoodle (skiphs in github) and certain forum staff.
I at one time was able to get a moderator to edit that original post when it was over a year out of date and I couldn't get in contact with Skidoodle to get him to update it.
Although I am a moderator my moderation powers/responsibilities only cover the Minecraft Discussion forums and don't extend to the Mapping and Modding forums.

I agree wholeheartedly that a Github Wiki is the way to go.  In fact I started one for the original Amidst repository but my editing expertise is/was lacking as far as making it well organized and presentable.

I agree that the new thread should be in the same forum where the old one resides. I just hope whoever is the original poster is stays around to keep the first post up to date.  If desired I will contact applicable forum staff to line up someone who can edit it if need be.

 I had already come to this conclusion some time ago and as Treer said I intend to post an announcement in PC Seeds with a link to the new thread. (I already have a download link to the Releases page of Github in my forum signature and have had for quite some time as I got tired of answering questions about where/how I was getting the world biome maps I post on a daily basis.)

The Wiki looks a lot better than my attempt.
I did edit one line to read: "read and display the world spawn" as opposed to "read the world spawn".
Remember that instructions for enabling and use of the history file needs to be added.
Same is probably true for the biome folder and color files. Note: I just noticed that Treer has removed the color profiles option from AE1.4.2.  It was still in AE1.3.9.

**Comment by stefandollase** [comment]
@BigAlanM Thanks for the clarification about the minecraftforum editing rights.

Also, thanks for the hint to the wiki in the old Amidst repository. I did not think there would be one. When I get the time, I will have a look at what we can copy over to the new wiki. Then, I will also add documentation about the command line parameters, the seed history file and the biome color profiles to this wiki.

Both posts, the one in "Mapping and Modding" as well as the one in "PC Seeds" should be created by the toolbox4minecraft account. This is the reason it was created. If I decide to leave the project in the future, I can simply share the mail account and minecraftforum account access with the new maintainer.

Maybe you can make a suggestion what should be posted in the PC Seeds subforum? Just create a new wiki page for it, we can remove it later.

- [ ] create a draft for PC-Seeds thread

Thanks for the offer to talk to the forum staff to edit the old thread. However, I hope that will not be necessary, since @skiphs decided to support the moving of the project in skiphs/AMIDST#92, but I might come back to your offer when there is no reaction after I ask for updating the thread.

I already noticed that you promote this new repository in the minecraftforum and I am really happy about it :-)

I do not know anything about the reasoning why @Treer removed the biome color profiles from AmidstExporter. Maybe, he can explain it. However, since the projects will be merged anyway, it does not really matter

**Comment by stefandollase** [comment]
@BigAlanM Did you already think about a good post for the Seeds thread in the minecraftforum. When you did, please [add it at the end of this wiki page](https://github.com/toolbox4minecraft/amidst/wiki/Forum-Entry-(preliminary)#forum-thread-for-seeds).

**Comment by Treer** [comment]
title change suggestion, to catch the 1.9 release wave.

Amidst now has 1.9 support, and a new home

**Comment by stefandollase** [comment]
Good idea. Done.

**Comment by stefandollase** [comment]
I close this issue, since all threads are created. You can find them here:

* [new primary minecraftforum thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/2626547-amidst-has-found-a-new-home) in [Minecraft Tools](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools).
* [new secondary minecraftforum thread](http://www.minecraftforum.net/forums/minecraft-discussion/seeds/2627219-amidst-now-supports-minecraft-1-9-and-has-a-new) in [Seeds](http://www.minecraftforum.net/forums/minecraft-discussion/seeds).
* [announcement](https://www.reddit.com/r/Minecraft/comments/48e3he/amidst_for_19_now_available_locate_igloos/) on reddit in [/r/minecraft](https://www.reddit.com/r/minecraft).

**Comment by BigAlanM** [comment]
Just a quick note: Today the original thread with over 5100 posts was locked by Forum Moderator Alvoria at my request.  Also the original post of the thread was edited with a link to the new thread.

**Comment by stefandollase** [comment]
@BigAlanM Thanks, this was indeed a good idea, since there was quite some confusion.
