### ISSUE TITLE
Does amidst work for Minecraft for Windows 10?

### ISSUE THREAD

**Issue by BetterBite** [toolbox4minecraft/amidst#391]
I tried using amidst but it cannot find the .minecraft file?
Is there some reason why it won't work?

**Comment by moulins** [comment]
Amidst only works for Minecraft Java Edition, not for Bedrock.

**Comment by Zitchas** [comment]
Just to be clear, Amidst *does* work for Minecraft running on Windows 10, it just doesn't work for the version of Minecraft that one gets through the Microsoft store (which is specifically labeled "Minecraft for Windows 10").

(If your Minecraft title screen says "Minecraft Java Edition" it should work. Otherwise, it probably won't)
