### ISSUE TITLE
MC-131462 is fixed

### ISSUE THREAD

**Issue by MattSturgeon** [toolbox4minecraft/amidst#406]
[MC-131462](https://bugs.mojang.com/browse/MC-131462) is apparently fixed in 1.13-pre4, so 06f0e1d should no longer be required

**Comment by moulins** [comment]
I disabled the relevant flag when adding 1.13-pre4 to the version list ([here](https://github.com/toolbox4minecraft/amidst/commit/32cb4a795b4fe1ce3aedc6ef6f45feafce8c1fbf)).

Even if the bug is fixed now, I think we should still keep it in Amidst for the relevant versions, as was done for the buggy stronghold algorithm in 1.9 snapshots.
