### ISSUE TITLE
Location of Villages appear to be Incorrect

### ISSUE THREAD

**Issue by Walshies** [toolbox4minecraft/amidst#423]
This is similar to the shipwreck location bug. When I went to a village using amidst it isnt there, but I found another village and that isnt on amidst.

**Comment by moulins** [comment]
Some villages displayed by Amidst won't spawn in game, because the terrain is too hilly. As Amidst doesn't generate the terrain, only the biomes, we can't really avoid these false positives.

However, all villages found in-game should be displayed in Amidst; could you give the seed and the coordinates of the village you found that wasn't displayed? (make sure you are using the latest version, v3.4-beta4)

**Comment by Walshies** [comment]
seed is -3086593819764553073 
coordinates: 
-1710.282
69
 -769.573

**Comment by moulins** [comment]
Thanks, added to the main issues for false negative structures! We still don't *really* know why these false negatives occur, but they should by fairly rare.

> also i went to the coordinates of a shipwreck and they seem to be off a bit

Yeah, shipwreck locations are incorrect since 1.13-pre7 (see #418), this still need to be fixed.
