### ISSUE TITLE
Request to write optimizations

### ISSUE THREAD

**Issue by burgerguy** [toolbox4minecraft/amidst#529]
I was looking to find ways to optimize the currently pretty slow versions of amidst. I am trying to get better at Java and have extensively looked through the Minecraft source and the amidst source to figure out how things work. I have already made a few changes I was looking to request to pull [seen here](https://github.com/burgerguy/amidst/commit/e90f278cfaad7b7b1f879bd2657b9337c67e4cd1). This includes:

Using LazyAreas more effectively
Skipping the Biome[] to int[] conversion
Fix support for snapshots 18w06a and 18w16a
Other minor changes

I had already made a pull request before I saw [this](https://github.com/toolbox4minecraft/amidst/wiki/Supporting-the-Development) but I have since closed it to ask for permission here.

On a more unrelated note, when I made that pull request the Travis CI build failed and gave the following error:
`Expected feature release number in range of 9 to 14, but got: 8`
Could someone explain to me what this is referring to? I don't think it's Java build, because amidst is supposed to use Java 8. My .travis.yml file is identical.

**Comment by moulins** [comment]
Sorry for being so long to respond, I was a little busy lately :/.

You should open a separate PR for each change:
 - one for the performance improvements;
 - another for the fix for `18w06a` and `18w16a`;
 - etc

I've opened issue #546 to track the 1`8w06a` and `18w16a` bug, so I'll close this issue.

--------
> On a more unrelated note, when I made that pull request the Travis CI build failed and gave the following error: &lt;snip>

The Travis CI issue was fixed by #542, it should be working correctly now.
