### ISSUE TITLE
[MC-92289] Extra strongholds spawn in positions Mojang didn't intend

### ISSUE THREAD

**Issue by stefandollase** [toolbox4minecraft/amidst#59]
This issue provides a place for further discussion about how we handle [MC-92289](https://bugs.mojang.com/browse/MC-92289). We already talked about it in #42 and #33.

Quoting @Treer's response to my question from #33:

> > Do you think we should do anything before we release the stable version?

> I think wait until we know what's happening with the stronghold locations bug in the 1.9 snapshots. If it looks like 1.9 is going to contain this bug then release Amidst as it is, if it looks like they will fix it before 1.9 then hold off the release until we find out what they're changing it to. Either way we should be able to release a stable version before 1.9 comes out.

**Comment by Treer** [comment]
Searge just marked this as fixed, so when they release the next snapshot we'll be able to update the Stronghold algorithm.

**Comment by Treer** [comment]
I've committed the updates, I've somehow committed straight into master instead of it creating the Issue_MC-92289 branch here, and I think any attempt by me to clean this up is going to make things worse, but the code is there - feel free to move it into a seperate branch.

The Amidst4 refactoring has made this change quite hard, related code has been broken up and hidden away in various methods and patterns, I've tried to emulate Amidst4's existing structure with this change and it means I don't envy anyone trying to decypher how this stronghold code works. This could mean I haven't done it the way you would and you might like to refactor it yourself. For perspective, here is the same change in AmidstExporter: https://github.com/Treer/AmidstExporter/commit/a9d9fd4ca22322fec9e1878175dd2f3bee56bf1e
