### ISSUE TITLE
History file entries to provide more meaningful information.

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#70]
Since it's now possible to change Minecraft profiles on the fly (without restarting Amidst) it would be VERY helpful if  each entry written to the history file contained the name of the Minecraft version profile used. 

I've been editing the history.txt file to add this information every time I restart with a different profile.

I first was going to suggest that all that needed to be done was to  just write a line to the file with the current profile information when a profile is selected at startup and when the version profile is changed (Ctrl-W).

BUT!!!
It's possible to have multiple instances of Amidst running concurrently in the SAME folder.
I tend to do this so that I can compare two seed maps produced by different world generators, specifically PCMCv1.6.4  vs. post-PCMCv1.7.2   or  PCMCv1.8.9 vs. PCMCv1.9

Doing this causes all running instances to update the history.txt file with no way of knowing which instance made the entry and which version profile was used.

**Comment by stefandollase** [comment]
I will look into this now.

**Comment by stefandollase** [comment]
This is implemented by #73. I added the recognised version name instead of the profile name or selected version id. I also added the comma as a separator between values, so it is easier to parse, if anybody wants to do so.

Note, that even though this is a feature request, I include this into the v4.0, because it is a change that would break the storage format later on.

**Comment by BigAlanM** [comment]
Fantastic!  Thank you!
