### ISSUE TITLE
Biomes from MinecraftInterface

### ISSUE THREAD

**Issue by burgerguy** [toolbox4minecraft/amidst#712]
I’ve started working on an implementation for fetching biome names from the MinecraftInterface. This means that we don’t have to have version keys for every biome name. Before I start, when I say `MCBiome`, I mean the biome class used in Minecraft, and when I say `AmidstBiome`, I mean the Biome class used in amidst. Also, when I say a new method, I mean a method that I have created for the implementation. The way that I’m implementing it works like this:

1. `AmidstBiome`s are initially made as public static finals with preset names in the `AmidstBiome` class. The name of the biomes are not final.

2. MinecraftInterface has a new method for getting an `<Integer, String>` map corresponding with MCBiome IDs and MCBiome Names. The map is generated by getting every MCBiome it can find in the `MCBiome` class.

3. In each MinecraftInterface’s constructor, it calls the new static method `AmidstBiome.createMinecraftBiomes(this)`. The `this` is the MinecraftInterface that is calling it. This method gets the map from the MinecraftInterface parameter, and does 2 major things with it.

* The first thing it does is replace the names of the biomes already declared in the `AmidstBiome` class by looping through the map, getting the corresponding `AmidstBiome` by its ID, and calling the new `setName(name)` method.

* The second thing it does is create a static map of biomes that are valid to the last MinecraftInterface passed in `createMinecraftBiomes`. This is only used for the biome widget so that it doesn’t display biomes that that version of Minecraft doesn’t support.

I have not created a PR for it yet due to it being in a very early stage, but when I do I’ll close this issue.

**Comment by moulins** [comment]
There are good ideas here, but I don't like the fact that the biome list becomes global mutable state.

I would instead propose a refactoring in two stages:

- Remove the `name` (which should actually be `displayName`) and `defaultColor` fields from the `amidst.mojanapi.world.biome.Biome` class and create new classes in `amidst.settings.biomeprofile` to handle them. (The biome color is already determined by the current biome profile, it seems logical to completely move it here).

- Use the actual Minecraft biome name (i.e. `minecraft:plains`) to identify a given biome. The issue here is the fact that biome names changed in [1.13-pre5](https://minecraft.gamepedia.com/Java_Edition_1.13-pre5#Changes), I'm not sure how this should be handled.

- Add the `MinecraftInterface` method you've proposed, mappings Minecraft biome names (`minecraft:plains`) to biome indices (`1`). Then, we can remove the global `Biome` list, and instead create a separate biome map for each world, containing (as you said) only the biomes supported by the current Minecraft version.

**Comment by burgerguy** [comment]
I'm going to close this and open up a pull request with my proposed changes.
