### ISSUE TITLE
grid label toggle, increase maximum restricted zoom, set zoom scales

### ISSUE THREAD

**Issue by Delvin4519** [toolbox4minecraft/amidst#722]
There are a few minor features I'd like to see tweaked.

1. One is to toggle numerical labels on or off on the grid, separate from the grid lines, i do not like how only either both are on or off. With the hover over, I can see the coordinates, and sometimes I just want to see the map with the grid lines so I know where the border is without the numbers clogging up the view.

2. Another thing is the restricted maximum zoom, right now, when zooming out, the pixel ratio goes to somewhere around 10.5 blocks per pixel, which is very odd. It would be nice if I can zoom it out to be exactly 16.0 or 32.0 blocks per pixel in the restricted setting

3. The zoom scale (blocks per pixel) never aligns by multiples of 2 for some reason. I also think there should be a toggle to set zoom scale level to be multiples of 2, so when you zoom in, each pixel is 1.0 block exactly, zoom out, it's exactly 2.0 blocks per pixel, then 4.0, then 8.0, and 16.0. The user can zoom in up to .5 blocks per pixel and zoom out, 1, 2, 4, 8, 16, up through 32 blocks per pixel, exactly. (unrestricted zoom). This would make the export to png more useful as then I can use imagine manipulation programs and make maps easy if each pixel was exact to a block multiple of 2 zoom.

**Comment by moulins** [comment]
> 1. One is to toggle numerical labels on or off on the grid ...

I'm not convinced by this; having the grid without the coordinates doesn't seem **that** useful, given that you can display the block scale if you need to gauge distances.

> 2. Another thing is the restricted maximum zoom, right now, when zooming out, the pixel ratio goes to somewhere around 10.5 blocks per pixel, which is very odd. It would be nice if I can zoom it out to be exactly 16.0 or 32.0 blocks per pixel in the restricted setting
>
> 3. The zoom scale (blocks per pixel) never aligns by multiples of 2 for some reason. ...

The zoom level starts at 4 blocks/px, then each zoom multiplies (or divides) it by 1.1, which means that it will never align to multiples of 2 (except at the starting value).  
To better align the zoom levels, I could change the factor to `pow(2, 1/8) ≈ 1.09`, so that 8 zoom levels correspond to a factor of two. Would this be enough for your use-case?

**Comment by Delvin4519** [comment]
for the zoom level, yea, it should work

**Comment by burgerguy** [comment]
That weird decimal that you're seeing is due to float (or double) imprecision. You can't avoid that with any traditional means other than using a BigDecimal, which impacts performance. I'd be surprised if it gives ANY notable difference, even when we're talking about something this small and volatile to changes like zooming and scale.
