### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by OllyEland** [toolbox4minecraft/amidst#768]
I put in a seed for it and amidst got it incorrect

**Comment by hippo211** [comment]
I used this to fid an end 
city but didn't lead me to one even though it said one was likely their

**Comment by bnjw5jhyxn** [comment]
> I used this to fid an end
> city but didn't lead me to one even though it said one was likely their

It isn't possible to guarantee that an end city will generate at a particular location. If you make many copies of the same world with the same seed and go to the location of a likely end city, it will generate around 85% of the time (https://github.com/toolbox4minecraft/amidst/wiki/The-End-map#user-content-what-are-likely-and-possible-end-cities). That's why Amidst refers those locations as "likely" end cities and not "definite" end cities

**Comment by moulins** [comment]
As previous comments said, End Cities cannot be determined with 100% certainty; closing this as invalid.
