### ISSUE TITLE
Does Amidst run when offline?

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#77]
When I copied the crash report to enter into Issue #71 I found that there is a notice in the "versions.json" file from Mojang that states that it's moving from https://s3.amazonaws.com/Minecraft.Download/versions/versions.json.

 "__comment": "This URL is being phased out! Please update your scripts to check https://launchermeta.mojang.com/mc/game/version_manifest.json instead. Thanks <3 --Dinnerbone",

1.  I suspect that this needs to be changed in the Amidst code. 
NOTE: The new file, version_manifest.json, has another parameter in each version entry labeled "url".
2. What happens if Amidst is run on a machine that doesn't happen to be online at the time?

**Comment by stefandollase** [comment]
You can run Amidst completely without an internet connection. It uses the internet for three reasons:

**Checking for updates**

This will just be skipped.

**Checking for the current version list**

This will fallback to a possibly outdated version list which is included with the Amidst jar file. This may cause an issue where a profile that uses the latest version will now use the latest version included in the outdated version list. However, there is nothing we can do about this, really.

**Loading player information**

The skin will fallback to the Steve skin while the player name will fallback to the uuid.

You made a really good discovery there. I will create a new issue for it, since the main question here is answered.
