### ISSUE TITLE
Highlight Biomes

### ISSUE THREAD

**Issue by k4mbing** [toolbox4minecraft/amidst#824]
it keep resetting, 
in the previous version , the highlight biomes i choose is stay when i click new seed

i hope u get the point
*english not good

**Comment by JuniorJedi490** [comment]
The issue is as follows:
When using "New from Random Seed" with highlight biomes enabled, highlight biomes becomes disabled, and which biomes were selected is lost.
Here are screenshots before and afterward, which demonstrate the issue.
![Before](https://user-images.githubusercontent.com/61092338/88480423-ba9edd80-cf23-11ea-9033-5333daf92822.png)
![After](https://user-images.githubusercontent.com/61092338/88480424-bc68a100-cf23-11ea-8d41-d08b1e73c9b2.png)
