### ISSUE TITLE
Comments on latest Beta release

### ISSUE THREAD

**Issue by BigAlanM** [toolbox4minecraft/amidst#84]
In this case Beta 9:
I do not like the layers menu in this release. Please revert to the one in Beta 8.
Not knowing which layers are active is quite troubling.

Question: Is the existence of the DOS window a temporary troubleshooting feature or permanent and is there no way to turn it off?  Closing it causes the regular Amidst window to close also.

I definitely like the new history.txt format.  
Being comma delimited will make it easy to import a history file into a spreadsheet for cleanup and sorting.  THANKS!

Make sure the Wiki explains the information displayed in the debug information.

Obviously the icons haven't been changed yet.

**Comment by BigAlanM** [comment]
Something that's probably been in the last several versions:
The email address and the link to this repository in the about screen aren't able to be copied with a highlight and Ctrl-C nor are they clickable to open the default mail client or browser.

**Comment by stefandollase** [comment]
Regarding the Layers Menu: The difference between the old and new version is, that Amidst now uses the native Windows look and feel again, as opposed to the default Java look and feel. Amidst v3.7 also used the windows look and feel on windows machines. I never meant to change this for windows. I only wanted to change it on Linux: The Linux look and feel looks kind of odd, so I wanted to switch Linux to use the Java look and feel. However, I made a mistake while doing so, which caused Amidst to use the Java look and feel for all Operating Systems. This is the reason for changing it back.

By the way, you can see which layers are active in the current version. The icon of the active layers has a slight, light blue border. However, it is really hard to see and not user friendly.

So your suggestion is to switch windows over to the Java look and feel? I don't see anything that would stand against this. As I said, the only reason to use the native Windows look and feel was that this is what Amidst v3.7 uses. However, since this is not really user friendly I will change this back.

- [ ] switch Windows to the Java look and feel

---

The dos-box is a side-effect of me fixing #40. I don't know how I missed the extra console window when I tested the exe file... I will remove this in the next release.

- [ ] remove console from Windows wrapper

---

You are talking about the debug information in the debug widget, right? I will add this to #66.

---

I don't know the plans of @Treer for when to integrate the icons. He did not yet create a pull-request for it. I guess he is still working on them.

**Comment by stefandollase** [comment]
I must have missed your second post when I was writing my answer. You are right, the information are not copyable. I will look into this when I get the time.

- [ ] make information in About window copyable

**Comment by Treer** [comment]
I've made pull request #93 for the icons. We can always replace the new witch icon if an artist comes up with something better.

**Comment by BigAlanM** [comment]
I just took a look at the layers menu and, Yes, now that it has been pointed out to me, I see that the active layers ARE indicated by a blue background around the icons.
Now that I'm aware of that I have no problem with the that part of the UI.
We need to make sure that information is in the Wiki.

And, yes, I was referring to the Amidst debug widget and the Wiki.
(Assuming the debug widget stays in the final 4.0 release and I can't see why it wouldn't.)

**Comment by stefandollase** [comment]
@BigAlanM It is probably a safe assumption that you are one of the most intensive users of Amidst. Thus, there are probably many other users out there which missed the blue background (it is really hard to see). This is the first reason why I will not switch back to the Java look and feel. The other reason is that this requires us to only support one look and feel for all platforms. Also, the user does not really see much of the GUI elements: The menu, some dialogues and that's it.

**Comment by stefandollase** [comment]
And I again, I missed a part of your post. The debug widget was already part of Amidst v3.7 and there are currently no plans to remove it. It is not displayed by default, so it should not confuse the users.

**Comment by stefandollase** [comment]
There is only one remaining task in this issue, which is a feature request and currently not high-priority, so I created a new issue for it to be able to close this one. See #95.

**Comment by Treer** [comment]
Just wanted to chime in with support for turning off "native" Windows look and feel.

Java's "native Windows look and feel" looks so bad with radio buttons I couldn't tell if it was supposed to be "Flat UI" or if it was simply buggy, and there was no way the user would recognise the radio buttons so I ended up converting AmidstExporter to generic LAF radio buttons. The icon selection/highlighting is also bad - as you were discussing.

I think there's less expectation for gaming related apps to look native, and Amidst looks fine for its purpose. The Java LAF is clear, and as you say, there's not many GUI elements visible anyway.

**Comment by BigAlanM** [comment]
If anybody is interested a user has found a seed with over 40 igloos around spawn.
They've even done a video of them and visited quite a few.
SO, it seems that Amidst4.0 is quite accurate at predicting the locations of igloos.
Of course, that doesn't mean that it's reporting ALL existing Igloos.
Or does it?  Is there much ambiguity in the Igloo placement routine?

Here's the thread: http://www.minecraftforum.net/forums/minecraft-discussion/seeds/2625548-1-9-ice-plains-seed-with-40-igloos
Seed: "-8473157689949562725"

WRT reported locations:
Amidst reports one at 4136, 744.  Flying, I teleported to 4136,100, 744 and found that I was 2 meters NW of the NW corner of the Igloo's basement.
Amidst also reports one at 3848, 856. Teleporting to that location I found that I seemed to be farther away from the Igloo. This one doesn't have a basement so it's hard to tell.
