### ISSUE TITLE
Request: Loot checker (enchanted golden apple finder) With pictures

### ISSUE THREAD

**Issue by scarifyFX** [toolbox4minecraft/amidst#930]
This feature which I am requesting would simply check all the loot in chests like dungeons, desert temples, and other structures for certain stuff which you can either select from or the devs will just add the rarest stuff by default. 

I personally like the second one and if you were able to choose what loot it had to be to pop up. If i chose Enchanted golden apples the chests will only appear when the chests include the specified items.
![idea-for-amidst]
(https://user-images.githubusercontent.com/47931007/103912585-c401b800-5107-11eb-8dc4-85d289a8eb45.png)

**Comment by burgerguy** [comment]
This is not an easy task, and it would probably significantly slow down amidst. This would have to be off by default, as there are many factors that go into loot generation. Each different structure has a different loot table. Each structure's rotation has to be calculated so we find the correct position of the chest. We have to simulate the loot actually being generated, which means going through every slot for every chest in every structure. Also, chests may end up not getting generated due to the terrain. We have no way of figuring out if this happens, so we just have to assume they all generated correctly. Finally, we have no way to tell if any particular world has any datapacks loaded (this could probably be fixed when importing a world, but not a seed). While it may be possible, it would be really difficult, and amidst needs more different changes before we get to this. I haven't touched amidst in a few months due to working on other projects and burnout with this. However, if development does end up starting back up, this would be a pretty low priority.

**Comment by moulins** [comment]
As @burgerguy said, implementing this would require Amidst to essentially generate the whole structure in order to get the proper seeds for each loot chest, and *then* simulate the loot drawing process to determine the contents.

This basically requires reimplementing a whole lot of Minecraft code, and would probably slow down world generation, so I don't see this being realistically possible.

Closing as out-of-scope.
