### ISSUE TITLE
Feature Request: Seed Finder

### ISSUE THREAD

**Issue by Oonezumikamisama** [toolbox4minecraft/amidst#958]
Would it be possible to use the concepts of amidst to search for seeds that meet certain criteria? For example, finding maps with all biomes and structures within a certain distance of origin?

**Comment by Boobies** [comment]
Seems outside the scope of Amidst. There are seed finding tools to help with this.

**Comment by burgerguy** [comment]
This feature actually used to be in amidst, but I’m not sure what happened to it. I know there are other tools that can help with this, though.

**Comment by moulins** [comment]
A seed-finder was indeed in development for Amidst, but it was never fully completed, and the massive slowdown of biome generation in Minecraft 1.13 made it not very useful anymore.

Since then, other external tools have appeared that can search seeds much more efficiently than Amidst ever could (e.g. [Cubiomes](https://github.com/Cubitect/cubiomes-viewer), that fully reimplements Minecraft generation in native code).
